version: '3.7'

services:

  mysql-db:
    image: mysql
    container_name: mysql-db
    hostname: mysql-db
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./databases:/usr/databases
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"

  # mysql-workbench:
  #   image: linuxserver/mysql-workbench:latest
  #   container_name: mysql-workbench
  #   hostname: mysql-workbench
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - ./databases:/usr/databases
  #   ports:
  #     - 3000:3000
  #   cap_add:
  #     - IPC_LOCK
  #   restart: unless-stopped
  