version: '3.7'

services:  
  pg-db:
    image: postgres
    restart: always
    container_name: pg-db
    hostname: pg-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./databases:/usr/databases


  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "ayoubhost0@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - ./databases:/usr/databases
    restart: always
    ports:
      - "5050:80"

  # adminer:
  #   image: adminer
  #   hostname: pg-adminer
  #   container_name: pg-adminer
  #   volumes:
  #     - ./databases:/usr/databases
  #   restart: always
  #   ports:
  #     - 8080:8080

    